# Run `travis lint` when changing this file to avoid breaking the build.
# Default JDK is really old: 1.8.0_31; Trusty's is less old: 1.8.0_51
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: false
dist: trusty

cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod a+x mvnw
  - chmod a+x travis/publish.sh
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "AXbGxe+jBpmwirQ2U60XuwmBklJlRroCandavy48rKLSadPc+Kkc5ftx+io/0cI3we0OS3d/RO7fkSU8OGzkr5pVrB/1Ta0Osui8Ok7Xxwwqq/SF2zWjtfZqgjtfIGMqFGeu2pZXUYZoDzG2oSWZouY12oXwbiE0ml5Ws0ujqhkEsJTfKmZiiwPJ/9KE5kx8m4tJBDWNEJCQL3MFN57zpq+3SFZACuzKcYWCFCPt492/52u0tzaS/AtvQ8OToCayC8bD0/BkvJ17E4P3ylzXt6N7cLvy3CLfMPJDxb34dHau6YslnWAVp8vqR1Jm8huv3lU3Po+5T8bAnZLiLcnWoDxJMR/NcLAvop+Jg//CMiYehJDfHLeAAxpozlpT/+5eAmfedYka7o+oUTsdI2IA8Dlw+PTVAFxCbYEL2CpuHziNQzfH6ZygRH05494sDeAsbUyoTDV8uMDMiHDSotBfQfukV2UhSGfmt3oYl6TgzguUBOwZI0YvvxfoVs5JsYgd2VWpxENmG24GIsFzSzWL9L96hzGZPstl5fK8AnPYFksnmQacn5RjOD+fYs4yDTKgRRvvz/aKTVQgQPh5/xrJYvN1fsXnbCgfMRh20J0Vu5bdHZR32r21Qgm0OH4zcSQBCX+sHCTZqXL2O9xeEGhk+5AihrKsP8QLy9NW2n3Yr74="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "PAtbtImeyHnjFR+yPVKggZgXb4oMXchM6YV3+qoYs6LExiqhwRPe4e+gAhfLESHUjiEoixAM77eAuk3Cqpklwtpy3Qwh3ptDtNm1d3VycDbhMVHkeIGaCJlHTitJHwegAHedrqH4qS3sRCG1Ke5Dxs1z1NtuLnIKhoiWKMW9SdNuLt+Wo+uYJnlr2Z78AVrChSsV4CiaJ5jZlFhRHO+cf22Xdx69Z2Imh7/3X+WBXIKqqNewegBlzvtQzZsknhFHmQV8UTJ1lCw6EcGOw5DXqqcRGmkRMsITeGMaUMd21Es2MeIHVsNS6aysLeAF15pbo3C9nhGJ11JWwNaeBVSpK+s8friNEOssJdvn+2W/NKrEHeKcEDwZRqKbOqUeGkwHb4n2nZd3oqc6/0O4Wf3q4bB1Dsh1PpL0tE5oeIbeUT0JMpk+MHIxzHyt5HuPnNqCk09psNbr110DiYNNddJKZOcv/hfxTuao55tbcg7C1tWYYcFxyMN3hE+EOEqhs3e4vOldFZSuF4/3lLYKBPl+Uin8eIUdzNQ01L3iy+FdB1haLS9V+kr72ZYABW0VdAj3Sw2GGsLsv5Xw2p8U3rcJBRm4mzrMSdfdN9YX2pOA/1Ch9rOiercKoy0hg2Q8PkORBJcOKS4uGPAAqrazAkpdih+sDTn7Sq+6sN1UNUR33fw="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "n8Vv4rxhnRpLzhqj3j/iuduN4GeeB8UnyIS/mXnwViZ88L/EwGzpwXkV42igoXpTlafZzCRPwQC8q9hcut0T37F6cbVW8S1oGc8BdLNwiHve8JLRdA4f+0HUgzQeS8N/o2Dkgf41Ku105NR8JXtCezi7NxaL73ugp5NpqGKHriM91sYjQh7iU+2u7HxzGWPVt3DYKL5Qhvbr41FQCi01pRwOf51Xj4UCbn8xle0lEGXsaI1sBl+lABsLhIl5Eoc97GxFM9TXiKP35/BDlJ12Y9pa6i1swbhb5sgS/Zcbr8px55+1qa/AcG9lHoSwwoqwTlDLuWKC9TJ7NhwzkYa0w20/k5pfWYyO+W69JWb3+WEOObCii1td6D+u9Cyy8IL9cXTedADaBEQCfIITqXMqI311Lt3mR4YLJ3q7JiHs8YBoLQb6xpkeZqHbhWXdIuuOyMBlkO0nSpfXend1Skzwok0s0iIsOIYjjRe/QVpKFlQECDxJDUPQqAarbhaodh5wL50t71+kYTYmw5uou3Qb+Cm5ZUkJmK01qya6lE3Oa0GHTJiK5qiciA0O0yVQtf7uwuBnRvN/b6EvwWdJpTUUYYM25yBY4v8oI/z4gcD0RMC0AZVj8em6KmbWhYduSDLgsNm+EYQ/9ziJTYEWP2Obd4BhOcSVxUEPn7aLVz6WGtw="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "Oz0QJvLnIwcpvwBC3Iib/bs4gFvSqEXDOQ2/tm8EplptY9w7X7nSXUobhjzimmEMOLjdYtraZBek0NtN/cKVAc4zzxyzkpao1YXa0AZZmB9zeirxBf6a1lBjZtK+Kl95ZrgrkKNa+MdYf9g1CGUSjwJs04pOGDlQJsqJvCto6iAFjdMmlktshypxVW2cPLVdpzwy0LMXfUG5+Fhzg6GqKP/M35gc/XxeryNcsFWkpfq+UJ1BvuK1phrNo5kWoljYm5ORkOWNSb7gwF4gviXfNZQef103UxObL3bGbR57CA6dXPUut6Y8JIhw5cWSYmFEWEMxZmjUGalM4NzekTgBNlIyaUJZaczJxyqzU96odEvadTZHgooLkO+33XBr5PyhFhDtjt0ym4tDHyp3vs3V864Rw4TohkYbxtNNuNd2H5WZFClULPEg6WrIlo+MGwHqhkLq4xwcrIw4WrcOrEpN95zZDzDbgFNSuq10joxoYkMtIFapPT+OdzyFvC90XpOyNUev2hlJWUrsiikcvecf/+9KP4JNsy3OG3ak4jk9Cwg/zYTDkzVJX7BkKQeCAFmS83iPi/Th4G0myN9VH4X+sa1qgPI/Bh9eSwjzLr+sgcMXmgD9GWUZ5JNAJ+sN5eupu5RGPoIshm0l0ZuNEQKSEvm/3aSsV6hVWrIml1FBtfk="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "i6GFKMh/p8i51eUxftJYECEzAH980INemOYoDzRMqBF/UdlvIk7JyA7/T7/+TvNv+lOoJuqVaz+0TMe3Nx/Ytb3mV0DKRaBdGghHYcZh4k2oY4VyUtFXUh/JVKEH2fmPaAstoq4ncrC3W0fPDWONXto0xqdgukkB7/SUwm4AMfJvFHoY8ygUne6Ul1NOudXU+LVlcwM/Wx38wJsDL6yYtB9mDwNpCnlvZtjTo9zbpJJjjuXnjkDhMZK4123BX91Y8nBxtrOLMLZgi6PG+mgNmOSxU4T2f516ozKnR2FKYeD48l+PQJro2JGzOceHjDm2XhGzO8k0OORTRFIm+kQr0qxlV0ADzZr9U0oATXup7nsDVAa4XY3nJI/zdQ4DkVAC+yxiKqy30QIxiaX7m2vaIN2fq2JjtUl99NkJFN/OaQiKvhvDUrIrEZAZryU1wr0IEfnvxcWvcir0U8fp+3BWFGQvtdwMZeRvebTafDSDAcV/BJdYfkfMa7iC50t3kF7ZrUEm3sA3Vnhugm1xN263bK+YVhHoOlLjsBTzOAhHUIyarYjciZjrIB1YGO8jR7VI3i1WZhUGnzlqFoB3vfadQ+z3tjNhm1DnmD+PYtxBC0peboOAAxU2Ls+KCPOxp5b6OvJO8SD45cfSI/ieXkJDelydPVpHy2llslbPwjPmHhE="
